### PR TITLE
Nalexander/bug 836790 data available

### PR DESCRIPTION
**Pull request by ncalexan**
This is working well locally.

### CODE REVIEW

**Comment by rnewman** [comment]
Theoretically this is a scary change, but it looks good to me, and you have tests. Let's get a build to QA and get it ready for ship and uplift.

**Comment by ncalexan** [comment]
New PR is rebased on develop; final three commits added.  Pretty straight-forward -- don't allow null infoCollections at all. @rnewman works for you?

**Comment by rnewman** [comment]
LGTM.

**Comment by ncalexan** [comment]
Landed on fx-team.

**Pull request closed without merging**
