### PR TITLE
Bug 808813 - implement Android account.

### PR DESCRIPTION
**Pull request by ncalexan**

### CODE REVIEW

**Comment by rnewman** [comment]
f+.

**Comment by rnewman** [comment]
Land the 808813 bits.

**Comment by rnewman** [comment]
scrypt helper looks good modulo comments.

**Comment by rnewman** [comment]
Fragment UI code looks OK, but haven't seen it. Also, let's not log passwords :P

**Comment by ncalexan** [comment]
This was only ever supposed to be Bug 808813 (which I just landed on elm); the other stuff was me re-using my trees.

**Pull request closed without merging**
