### PR TITLE
Bug 901622 - Invalidate ProfileInformationCache...

### PR DESCRIPTION
**Pull request by mcomella**
by bumping version number.

Also took the liberty to update some licenses.

### CODE REVIEW

**Comment by rnewman** [comment]
Good comment, but I also wanted a specific history for what changed between v1 and v2. That can either go in the case statement, or it can go in a comment above the version number, but it ought to go somewhere. Something like:

```
* -: No version number; implicit v1.
* 1: Added versioning. Bug 878670.
* 2: Bumping in Bug 901622 in order to regenerate add-on set after landing Bug 900964.
```

**Comment by rnewman** [comment]
Also, did you see my test comment?

**Comment by mcomella** [comment]
> Also, did you see my test comment?

Yep, almost done.

**Comment by mcomella** [comment]
@rnewman: All done addressing comments.

**Comment by rnewman** [comment]
Looks good. Double-check that it works on a phone and land it land it! :+1:

**Pull request merged**
