### PR TITLE
739906 - autocorrect, 717707 - hibernation on credential entry, 705767 - account validation

### PR DESCRIPTION
**Pull request by liuche**
Added in UI feedback for account failure using new strings.

### CODE REVIEW

**Comment by liuche** [comment]
Rebased to include sync key validation, cleaned up strict mode policy violation.

**Comment by liuche** [comment]
Fixed test hanging by removing an unnecessary nested WaitHelper.

**Comment by rnewman** [comment]
Not a blocker, so this pull request languishes for a couple weeks.

**Comment by liuche** [comment]
Rebased to pull #191.

**Pull request closed without merging**
