### PR TITLE
Bug 888086 - Use StringBuilder in sync/Utils.java

### PR DESCRIPTION
**Pull request by mcomella**
Continuation of #334.

Did not do the alternative benchmarking mentioned in #334.

### CODE REVIEW

**Comment by rnewman** [comment]
Looks good, but I'd love to have you spend ten minutes on round-trip tests through byte2hex/hex2byte.

**Comment by mcomella** [comment]
@rnewman: :thumbsup:

**Comment by mcomella** [comment]
@rnewman: ^ Just making sure you didn't lose the notification (take your time).

**Comment by rnewman** [comment]
LGTM. Ship it!

**Pull request merged**
