### PR TITLE
Bug 836780 - data available

### PR DESCRIPTION
**Pull request by ncalexan**
This might not be our long term strategy, but let's minimize our HTTP GETs with the architecture we have in place.

Those rebuilds?  So I can device test!

### CODE REVIEW

**Comment by rnewman** [comment]
Can't argue with this!

**Comment by ncalexan** [comment]
This tree actually works on device!  It's still clown shoes all the way: due to the way `begin` and `unbundle` work, we do a ton of DB crawling in bookmarks and history that might not be necessary.  But this at least reduces network requests.

**Comment by ncalexan** [comment]
rnewman: can I get re-review on this?  There were significant changes due to the way timestamps were actually handled.

**Comment by rnewman** [comment]
This looks fine to me. Needs rebasing on top of logger reorg, though.

**Comment by ncalexan** [comment]
Closing in favour of the rebased, updated, and re-tested https://github.com/mozilla-services/android-sync/pull/437.

**Pull request closed without merging**
