### PR TITLE
Bug 1022748 - use custom servers

### PR DESCRIPTION
**Pull request by ncalexan**
This accepts extras from `launchSetup`.  I went with `{auth:"url", services:{sync:"url"}}`, although I'm going to wait for comment from you and @ckarlof before committing to this.

### CODE REVIEW

**Comment by ncalexan** [comment]
This was purposely built in two stages: functionality, and then UX, the idea being that we might be able to uplift the functionality.

**Comment by ncalexan** [comment]
This was purposely built in two stages: functionality, and then UX, the idea being that we might be able to uplift the functionality.

**Comment by rnewman** [comment]
lgtm apart from some safety questions.

**Comment by ncalexan** [comment]
Landed.

**Pull request closed without merging**
