### PR TITLE
Bug 723230 - secreview meta bug.

### PR DESCRIPTION
**Pull request by ncalexan**
From the "it was there" files: try to move on a few of these outstanding P1's.  Also commented on open tickets blocking 723230.

### CODE REVIEW

**Comment by rnewman** [comment]
It makes `counter` _safer_, because it's only evaluated once. It doesn't make it `safe`, because accesses to `long`s in Java aren't atomic.

For a logging operation, I'm happy with "fairly safe", which is why I didn't synchronize this counter when I wrote the original code. The overhead of synchronization or an `AtomicLong` is unnecessary. `volatile` would address the issue.

**Comment by rnewman** [comment]
r=me with `volatile` for the counter and `private` for `enable…`. Merge when done.

**Comment by rnewman** [comment]
Actually, hold off on the merge, please. I want to get Marina's stuff in in one go, so I'll merge this afterwards. Thanks!

**Comment by ncalexan** [comment]
I rebased to develop, borking the original commit comments :(  I hate that.

**Comment by rnewman** [comment]
Good good. Could you flatten the review comments into the main commits? Makes it easier for me to land on m-i.

**Pull request merged**
