### PR TITLE
Bug 734521 - consume response audit

### PR DESCRIPTION
**Pull request by ncalexan**

### CODE REVIEW

**Comment by indygreg** [comment]
I would argue that running tests in a non-deterministic order is better. Otherwise, you may inadvertently rely on state between tests.

**Comment by ncalexan** [comment]
Hi Greg, I think I agree.

In this case random order actually helped hide the problem -- it was an interaction between lots of tests being run in a certain order by maven that failed (including alphabetical) and almost any other order succeeded.  Happy to fixup and have this random.

**Comment by indygreg** [comment]
Wow, I think you hit the exception.

**Comment by ncalexan** [comment]
Running tests in random order landed as part of Bug 709329; putting consumeEntity helpers added as separate part.

**Comment by rnewman** [comment]
Merged.

**Pull request closed without merging**
