### PR TITLE
Bug 1097220 - Extend client record format

### PR DESCRIPTION
**Pull request by rnewman**

### CODE REVIEW

**Comment by rnewman** [comment]
You probably care about https://github.com/mozilla-services/docs/commit/c3d68b257ace7985eb7b7571a9b95ab81b1f24f4

**Comment by ncalexan** [comment]
lgtm.  Can you manually verify that sending a tab between two clients with upgraded client records preserves the optional client fields?

**Comment by rnewman** [comment]
Sent from Android to desktop, retrieved via CLI:

```
  {
    "appPackage": "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",
    "id": "6hylTLQOYPKd",
    "commands": [
      {
        "command": "displayURI",
        "args": [
          "http://www.reddit.com/r/funny/comments/2modlw/my_work_gave_me_a_hard_time_for_calling_off_1_the/",
          "enQ9iVZLzRrN",
          "My work gave me a hard time for calling off. 1. The buses aren't running. 2. There is a driving ban and 3. My car is in the garage : funny"
        ]
      }
    ],
    "version": "36.0a1",
    "name": "rnewman's Nightly on jetfire",
    "application": "Nightly",
    "type": "desktop",
    "os": "Darwin",
    "protocols": [
      "1.1",
      "1.5"
    ]
  },
```

**Comment by rnewman** [comment]
Sent from desktop to Android via manual invocation of ClientsEngine.sendURIToClientForDisplay:

```
  {
    "device": "Nexus 7",
    "appPackage": "org.mozilla.fennec_rnewman",
    "id": "enQ9iVZLzRrN",
    "version": "36.0a1",
    "name": "Fennec rnewman on Nexus 7",
    "application": "Fennec rnewman",
    "formfactor": "smalltablet",
    "type": "mobile",
    "os": "Android",
    "protocols": [
      "1.1",
      "1.5"
    ],
    "commands": [
      {
        "command": "displayURI",
        "args": [
          "http://slashdot.org",
          "6hylTLQOYPKd",
          "Slashdot"
        ]
      }
    ]
  },
```

**Comment by rnewman** [comment]
I didn't remember that send tab carried the sender's ID with it! Neat.

**Pull request merged**
