### PR TITLE
Bug 843889 - factor tabs code that is not Sync specific out of org.mozilla.gecko.sync.

### PR DESCRIPTION
**Pull request by ncalexan**
Let the excavations begin!

### CODE REVIEW

**Comment by rnewman** [comment]
I disagree with one particular part of this: `org.mozilla.gecko.db` is part of the Fennec tree, as is the new destination of `CursorDumper`. Firstly, our deployment scripts don't play nicely with this. Secondly, it'll be confusing as heck for other developers that _some_ files in their directories are managed upstream. Thirdly, we run the risk of collisions (like Python!).

Pick a new subpackage — org.mozilla.gecko.background works, I think — and use that as the root.

**Comment by ncalexan** [comment]
Good point on the overlap with `org.mozilla.gecko.db` -- it's a pity that such a good part of the namespace is already taken :)  In fact, I think `org.mozilla.gecko.common` is too broad, and we should settle on `org.mozilla.gecko.background` for the common parts and then `org.mozilla.gecko.background.db` for our view on Fennec's datastores.  Does that sound good?

**Comment by ncalexan** [comment]
By "too broad" above, I mean that we don't want to put inject `mobile/android/base/common` into the Fennec namespace -- we want to inject `mobile/android/base/background/common` (or similar).

**Comment by ncalexan** [comment]
Rebased to develop and moved DB things to `org.mozilla.gecko.background.db`.

**Comment by rnewman** [comment]
DO EET.

**Comment by ncalexan** [comment]
Trees are closed and BMO is getting upgraded!

**Comment by rnewman** [comment]
Why do you think I'm here on GitHub? :)

**Pull request merged**
