### PR TITLE
Bug 772645 - concurrent Fennecs

### PR DESCRIPTION
**Pull request by ncalexan**
Apply following patch to m-i first:

http://people.mozilla.com/~nalexander/concurrent-Fennecs.patch

This is the Android stuff specific to supporting concurrent Fennecs, where concurrent means non-overlapping in the sense of not sharing an Account type.

Test APKs:

http://people.mozilla.com/~nalexander/fennec-concurrent-whoami.apk (org.mozilla.fennec_ncalexan, Fennec Sync)
http://people.mozilla.com/~nalexander/fennec-concurrent-official.apk (org.mozilla.firefox, Firefox Sync)

Creating/syncing/deleting Android Accounts worked well.  Send Tab seemed good, although testing it on device is strange because you need to force sync two Account objects.

### CODE REVIEW

**Comment by ncalexan** [comment]
Rebased and patch at http://people.mozilla.com/~nalexander/concurrent-Fennecs.patch updated.

**Comment by ncalexan** [comment]
Patch against Fennec is now at https://bugzilla.mozilla.org/show_bug.cgi?id=772645.

**Comment by ncalexan** [comment]
Rebased on top of Bug 764867 (https://github.com/mozilla-services/android-sync/pull/238) for updated branding that makes this usable.  Patch against Fennec and this are ready for review.

**Comment by rnewman** [comment]
r+ with the two comments in this PR and the nit in #238.

**Pull request merged**
