### PR TITLE
Clients Engine

### PR DESCRIPTION
**Pull request by emtwo**
Here's a rough start. Needs unit tests, but I did test as I went on my own account so it should be roughly good. Reviews please :)

### CODE REVIEW

**Comment by rnewman** [comment]
Please adjust commit message to be

  Bug 715796 - Clients engine stage. r=rnewman

**Comment by emtwo** [comment]
- Made some changes + addressed comments from here: https://github.com/mozilla-services/android-sync/commit/c0c8705
- Test (in 3rd commit) is still rough and has some failures with http requests, still working on it

**Comment by emtwo** [comment]
- Merged all commits together with all new changes
- Addressed comments from here: https://github.com/mozilla-services/android-sync/commit/a2e45d
- Includes generating client names
- Includes cleanup for abstracting SQLiteOpenHelper cache
- Includes more unit-y tests + tests using the MockServer
- Other small changes/fixes here and there

**Comment by rnewman** [comment]
The test server has a JUnit dependency, and Maven is compiling it in a non-test scope.

This isn't a problem in m-c.

Anything you move into `main` has to have no dependency on our test-only items.

**Comment by emtwo** [comment]
Last commit was: https://github.com/mozilla-services/android-sync/commit/c0f2cc

This commit:
- Factored SyncClientsEngineStage for easier testing
- Added ClientsDatabaseContentProvider
- numClients is accessed by through the ClientsDatabaseContentProvider
- Tests split up into record, database, content provider, and http tests

Todo: 
- more http tests - when shouldUpload returns false, crypto is null, etc
- test handleWBO
- Anything else?

**Comment by rnewman** [comment]
Marina: I split this into 5 or so commits and rebased it on top of current develop. It lives here:

https://github.com/mozilla-services/android-sync/tree/marina/rebased-clients-stage

**Comment by rnewman** [comment]
Replaced by https://github.com/mozilla-services/android-sync/pull/77.

**Pull request closed without merging**
