### PR TITLE
No bug yet: extract SyncConfiguration.

### PR DESCRIPTION
**Pull request by rnewman**

### CODE REVIEW

**Comment by rnewman** [comment]
@ncalexan: tests pass. Take a look? First and last commits are the meaningful ones.

**Comment by rnewman** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=963336

**Comment by ncalexan** [comment]
lgtm.  It cracks me up that the path to a better SyncAdapter instance is through a much, much worse SyncAdapter.  Sigh.  #shipping

**Comment by rnewman** [comment]
Merged.

**Pull request closed without merging**
