### PR TITLE
Bug 918465 - Record locale in FHR environment.

### PR DESCRIPTION
**Pull request by rnewman**
No tests yet. I'm still tired from Summit.

### CODE REVIEW

**Comment by mcomella** [comment]
@rnewman: feedback more or less done. I listed a few questions of things I'm unsure about (and thus might require better comments) and a bunch of nits (let me know if I'm being too pedantic).

**Comment by rnewman** [comment]
mcomella: incremental review?

**Comment by mcomella** [comment]
@rnewman: Done reviewing. I lost the comments from the first review so I don't remember if there were any glaring issues that needed fixing (but I remember a "lgtm w/ nits").

These comments are mostly nits so lgtm w/ any nits that you feel are relevant/important.

**Comment by mcomella** [comment]
Why are my commits here? Did you rebase onto `develop` properly? This might cause a strange merge issue back to `develop`.

**Comment by rnewman** [comment]
_shrug_

**Comment by mcomella** [comment]
via IRC:

<mcomella> rnewman: Is the DB guaranteed to upgrade?
<mcomella> rnewman: Wasn't that the issue with that one bug you refered me to? That that didn't happen
<mcomella> rnewman: Since we make some assumptions, I think, with the Env code that values such as "acceptLangSet" will be there

**Comment by mcomella** [comment]
You could test `HealthReportGenerator.getAppInfo` directly, but that's probably overkill.

r+ pending on the IRC comment.

**Pull request merged**
