### PR TITLE
Bug 753878 engines - second review

### PR DESCRIPTION
**Pull request by ncalexan**
This is not quite a straight rebase -- I rebased everything but also made some small changes.  Comments to come.

### CODE REVIEW

**Comment by ncalexan** [comment]
I have some specific comments and some general comments.  Specific comments first:

Fold the two Activities into one, in preparation for making one ConfigureSyncActivity that will be called from Fennec.  Think about the lifecycle of this Activity -- it's not clear to me that onResume is the correct place to configure the Account.  I think the user should be able to go away and come back to configuration.

**Comment by ncalexan** [comment]
General comments: no tests is not awesome-sauce.
- Integration tests for SyncConfiguration.blockingPrefs..., plz.
- Unit tests (to dummy shared prefs) for storing/reading selected engines to/from prefs, demonstrating handling of forms/history.
- Some tests explaining the gnarly userSelected/enabled/default logic would be gravy.

**Comment by ncalexan** [comment]
General comment:

Prefer once and only once, as in http://c2.com/xp/OnceAndOnlyOnce.html.

For example, in SyncAccounts you added two duplicate helper functions.  Use the more general one in the less general one.

Also, you added some nice general functions: blockingPrefs..., validEngineNames.  You even copy-pasta'd one of them!  You need to check where your new function is applicable and try to update the relevant places to use them.

**Comment by ncalexan** [comment]
General comment: Bug XXX at beginning of every commit message.

**Comment by ncalexan** [comment]
General comment: this is looking Pretty Damn Awesome.  Good work!

**Comment by ncalexan** [comment]
Re: updating config: I'm convinced.  I'll try to get to this tomorrow AM; I'm too busy plugging on another bug to context switch this back in.

**Comment by ncalexan** [comment]
Okay, this is looking really close.  I repeat:
- Integration tests for SyncConfiguration.blockingPrefs..., plz.
- Unit tests (to dummy shared prefs) for storing/reading selected engines to/from prefs, demonstrating handling of forms/history.

Then rebase this down to 5 independent patches, like we had before:
- Bug 753878 - Upload meta/global record with user selected engines to sync.
- Bug 753878 - Add activity for user selecting engines to sync.
- Bug 753878 - Add SyncAccounts.blockingPrefsFromAndroidAccountV0.
- Bug 753878 - Add ExtendedJSONObject.remove.
- Bug 753878 - Factor out SyncConfiguration.getEnabledEngineNames.

And we're good to go to QA.

**Comment by ncalexan** [comment]
Ooh, this is looking _excellent_.  Device testing works like a charm for me!

I have only one concern, and I'm not sure what we should do with it.  When you fire up the "Sync my..." dialog, make your selections, and hit "OK", you get a toast saying "Your preferences have been saved."  I don't think our users have the mental model of local preferences/remote preferences and that this will be confusing.

I wonder if we should prompt for a sync, either in the toast ("[Force] Sync now to update your preferences on all your devices.") or just by spinning one up (see `SyncAdapter.requestImmediateSync`).  rnewman?

r=nalexander after we address this.

**Comment by liuche** [comment]
I like the idea of requesting an immediate sync - this is what desktop does, right, instant sync? I can't think of any downsides to requesting immediate syncs, as long as Android can handle things like already syncing or sync disabled - anything come to mind (rnewman, nalexander)?

**Comment by liuche** [comment]
Rebased and added immediate syncing on saving selections.

**Comment by ncalexan** [comment]
I left this issue (requesting sync) open for discussion because it's more complicated than just requesting a sync.  What happens if the sync fails -- does this code handle not uploading meta/global and trying again the next sync?  (I think it will not.  We "complete" a sync even if the net connection is dropped after info/collections, which means `UploadMetaGlobalStage` executes... perhaps this pull is clever enough to handle this.)   Also, is our messaging good in that situation?  (I think not -- it's basically not possible to feed information about a triggered sync back to the shooter.)

**Comment by liuche** [comment]
nalexander, correct on the null argument for requestImmediateSync, fixed now.

Added an incremental clearing of selectedEngines, in case an engine stage doesn't run at all. Review plz, and I will rebase it back into the stack of commits. This should make partially failed syncs more robust.

In the case that meta/global fails to upload, selected engines will be tried on subsequent syncs until a success, when we will clear the updated engines from the selected engines pref.

**Comment by liuche** [comment]
New changes: commits following Part 4 (that should ultimately be folded into part 4).

These clean up engine upload behavior in the cases of 1) incomplete engines sync and 2) timestamp checking for local/remote meta/global to determine whether or not to upload.

**Comment by liuche** [comment]
Rebased on develop, added new test for syncing with an unknown engine, debug level logging for timestamp reconciliation (for observing clock skew between devices), and addressed review comments.

**Comment by ncalexan** [comment]
The test for making sure we don't remove a `new-engine` looks good.  However, I've forgotten what the consensus was around engine uploading with timestamps.  liuche, can you remind me?

**Comment by ncalexan** [comment]
Further to discussion in MV with liuche and rnewman: if two offline clients conflict, then first client to sync wins.  Further to discussion with liuche: r=nalexander after folding commits.  Any additional changes will be follow-up.

**Comment by liuche** [comment]
Merged into develop.

**Pull request closed without merging**
