### PR TITLE
Bug 709329 - 401 node reassignment - after review comments

### PR DESCRIPTION
**Pull request by ncalexan**
Hi rnewman, I would like feedback/review on one additional change, noted in the commits.  Then merge away!  The final commit, to randomize testing, is necessary until the HttpResponse consumption audit branch is merged.  (That audit was prompted by these tests failing, after all.)

### CODE REVIEW

**Comment by ncalexan** [comment]
Continuation of https://github.com/mozilla-services/android-sync/pull/103

**Comment by ncalexan** [comment]
This needed rebasing onto the tabs stuff, and I fixed the comment errors you flagged.

**Comment by rnewman** [comment]
See comments in ba1f454342e84ad5f2321f3c6aede11b382c832c.

**Comment by ncalexan** [comment]
All right, I think this addresses all review comments, and adds a comment with the bug number about ignoring store errors.

**Comment by ncalexan** [comment]
Just retested syncing an existing account on my Transformer Prime, and pairing a new account and syncing -- seems to get cluster URL fine.  Still can't produce a 401 to really work out the logic :(

**Pull request merged**
