### PR TITLE
Bug 762118 - Ignore readinglist items and folder for now.

### PR DESCRIPTION
**Pull request by rnewman**
https://bugzilla.mozilla.org/show_bug.cgi?id=762118

### CODE REVIEW

**Comment by ncalexan** [comment]
Is this waiting on tests?

Also, does `readinglist` need to be rooted in the tree (like the `places` and `mobile` folders)?

**Comment by rnewman** [comment]
You can review this part until I deliver tests.

Rooting in the tree will be part of the actual implementation of reading list sync; this just ensures that we never see them.

**Comment by ncalexan** [comment]
This part is fine, then.  The rooting came up when I started grepping for places and other similar (rooted) things.

**Comment by rnewman** [comment]
Here, have some tests!

**Comment by ncalexan** [comment]
r=nalexander.  Didn't get to landing this today, will try again tomorrow if I'm not beaten to it.

**Pull request merged**
