### PR TITLE
Bug 796187 - Send tab: usability tweaks

### PR DESCRIPTION
**Pull request by rnewman**
I ended up reworking the `ClientRecordArrayAdapter`, because despite being an `ArrayAdapter` it elected to manage its own array!

We now populate and connect it, then fetch client records and update the adapter accordingly.

We only fetch client records once, regardless of how many times you resume the activity. That should stop boxes getting unchecked.

And then the real work: check automatically if there's only one client to which to send, and make the rows slightly fatter.

### CODE REVIEW

**Comment by ncalexan** [comment]
How do you feel about displaying title and URL?  I like it.

**Comment by ncalexan** [comment]
I have one substantive complaint, and one possible enhancement, but everything else looks good.

**Comment by ncalexan** [comment]
Looks good to me.  If you are happy with displaying the title and uri, rebase this down and r=nalexander.

**Comment by rnewman** [comment]
Merged.

**Pull request closed without merging**
