### PR TITLE
Bug None: Update README to include testing info. r=nalexander

### PR DESCRIPTION
**Pull request by mcomella**
Testing info includes information about remote debugging and an example
usage with JDB. There is a TODO requesting more information for Android
unit testing.

---

Note: I'm a bit hesitant about adding a TODO to the README and the commit message format.

@ncalexan: Please review.

### CODE REVIEW

**Comment by mcomella** [comment]
> This is a good first cut. The README dupes a lot of testing.rst; can you cut the README way down and point to docs/testing.rest instead?

Right now the readme is auto-generated via `preprocess.py`. Do you mean you'd rather the testing section in the README to be something like:

> ### Testing
> 
> See [testing.rst](https://github.com/mcomella/android-sync/blob/mcomella/bug-none-docs-testing/docs/testing.rst) for more information.

Or something else?

**Comment by ncalexan** [comment]
Totally forgot about that -- now I understand why the duplication :)  I did that because you can't use `include` on github.

If you could fix up the bits about unit/integration tests, that would be great.

**Comment by mcomella** [comment]
@ncalexan: Made the changes in the added patch. Please review.

**Comment by ncalexan** [comment]
Closed via https://github.com/mozilla-services/android-sync/compare/d09a2bf88bfa

**Pull request closed without merging**
