### PR TITLE
Test CryptoMiddleware.

### PR DESCRIPTION
**Pull request by ncalexan**
I decided I wanted to understand how this worked, so I wrote tests for it.

In the process, I discovered that Crypto5MiddlewareRepositorySession didn't update its status, so I fixed that.

It is possible that these changes are connected to the intermittent failures we are hitting in TrackingStoreTest.testStoreRetrieveByGUID, but I am hitting them just the same without this patch series applied.

### CODE REVIEW

**Comment by rnewman** [comment]
Nick, would you please rebase this on top of your Cryptographer cleanup and re-push?

**Comment by ncalexan** [comment]
Rebased to develop.

**Comment by rnewman** [comment]
A few things:
- Check that missing method.
- Boilerplate.
- Please re-rebase on top of develop; if you already did so, apparently it didn't stick.
- Bug number on every commit.
- Please roll up commits like 2ecdccc into whichever other commit deserves it.

**Comment by ncalexan** [comment]
- Rebased onto develop and missing method reinstated (rebase issue?).
- Bug opened and bug number added.
- Rebase commits rolled into substantive commits.
- License boilerplate added.

**Comment by rnewman** [comment]
Merged.

**Pull request closed without merging**
