### PR TITLE
Nalexander/bug 966104 sync status listener

### PR DESCRIPTION
**Pull request by ncalexan**

### CODE REVIEW

**Comment by ncalexan** [comment]
@rnewman I folded in your earlier review comments, and reworked the `requestSync` function to declare hints:
- Android scheduling;
- local rate limiting;
- remote server backoffs.

These patches declare the hints, but the corresponding `FxAccountSyncAdapter` code to act on them will be a separate ticket.  I'm hoping this is enough for now.  Note: I have not device tested these patches yet, but will (of course) do so soon.

**Comment by rnewman** [comment]
Other than having two Part 3s, this looks perfect.

**Comment by rnewman** [comment]
As such, it's like traditional Jewish art.

**Comment by rnewman** [comment]
Ship it ship it

**Comment by ncalexan** [comment]
Landed.

**Pull request closed without merging**
