### PR TITLE
Inconsistency between javadoc param and method arg.

### PR DESCRIPTION
**Pull request by liuche**
Missed a javadoc param while refactoring. (engine selection for bug 753878)

### CODE REVIEW

**Comment by rnewman** [comment]
Include bug number in commit message, merge this in the same patch that you land on inbound, if you haven't already. r+.

**Comment by liuche** [comment]
I already pushed the engines patch to m-i yesterday, so I'll land this once I get confirmation that that patch made it into the tree.

**Comment by ncalexan** [comment]
rnewman: can you fold this follow up into your fixes for Announcements?  I think that will be next to land.

**Comment by rnewman** [comment]
Done. Closing this.

**Pull request closed without merging**
