### PR TITLE
Bug 840128 - Android client for Bagheera.

### PR DESCRIPTION
**Pull request by rnewman**
The only thing outstanding here is to wait for Bagheera 0.8 to be released, so that I don't break ci.mo when it merges.

### CODE REVIEW

**Comment by ncalexan** [comment]
Fly-by: code looks good.  Overall: not into this patch.  I see tons of deep dependencies into the Bagheera codebase, which is hardly stable; POM references to hadoop, hbase, zookeeper, and tons of other crap; and severe drift from our tight stand alone repository.

I'd like to explore another maven sub-project for this stuff -- at least for the testing stuff.

**Comment by rnewman** [comment]
Yup, I'd be happier with a cleaner dependency setup in a testing module, too.

**Comment by rnewman** [comment]
Note that all the POM references are test-only.

**Comment by rnewman** [comment]
Your wish is my extremely verbose command.

Note that there is a change to `preprocess.sh` that needs to be reflected in your parallel branch…

**Comment by rnewman** [comment]
Superseded by #301.

**Pull request closed without merging**
