### PR TITLE
Bug 755237 - Don't wait for history migration to complete prior to syncing.

### PR DESCRIPTION
**Pull request by rnewman**

### CODE REVIEW

**Comment by rnewman** [comment]
Waiting on QA.

**Comment by rnewman** [comment]
I seem to recall that this was reviewed. Someone put a name on it, please.

**Comment by ncalexan** [comment]
r=nalexander

**Comment by rnewman** [comment]
We elected not to do this… perhaps yet, perhaps ever. See https://bugzilla.mozilla.org/show_bug.cgi?id=755237 . Will close PR when the bug closes.

**Comment by rnewman** [comment]
WONTFIXED in August.

**Pull request closed without merging**
